### ISSUE TITLE
MixinBooter installs incorrectly when it's installed from the Launcher

### ISSUE THREAD

**Issue by 1gn4ac10** [Voxelum/x-minecraft-launcher#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Launcher Version

v0.44.6

### Operating System

Windows

### Architecture

x64

### Current Behavior

When MixinBooter is installed from the Launcher mod browser, it downloads the file "**mixinbooter-9.1**", different when its downloaded from the browser (which is **!mixinbooter-9.1**). This causes Forge to not load completely because its supposedly missing mixinbooter.

### Expected Behavior

When MixinBooter it's installed from the Launcher, it should install normally without causing errors (the probable cause for the error it's I guess the missing **!**)

### Steps To Reproduce

Simply install MixinBooter from the mod browser in the Launcher

**Comment by ci010** [comment]
I also observe this behavior (!mixinbooter having ! before the file).

One clue is I use the [filenamify](https://www.npmjs.com/package/filenamify) library to normalize the filename, which replace illegal filename char to ! by default. For some reason, the first char of mixinbooter file is replaced.

I need to take a look in detail.

**Comment by ci010** [comment]
Will fixed in next release

**Comment by 1gn4ac10** [comment]
It seems it's still happening. At least with mixinbooter. Just the same thing, the file doesnt have the **!** at the start
